package io;

public class DataBase {
public static String getNames() {
	return "Aarav\r\n"
			+ "Abhishek\r\n"
			+ "Aditya\r\n"
			+ "Akshay\r\n"
			+ "Aman\r\n"
			+ "Anand\r\n"
			+ "Aniket\r\n"
			+ "Arjun\r\n"
			+ "Ashwin\r\n"
			+ "Bhavesh\r\n"
			+ "Chaitanya\r\n"
			+ "Deepak\r\n"
			+ "Devansh\r\n"
			+ "Gaurav\r\n"
			+ "Harsh\r\n"
			+ "Ishaan\r\n"
			+ "Jatin\r\n"
			+ "Karthik\r\n"
			+ "Lokesh\r\n"
			+ "Manish\r\n"
			+ "Mihir\r\n"
			+ "Nitin\r\n"
			+ "Pranav\r\n"
			+ "Rahul\r\n"
			+ "Rohan\r\n"
			+ "Female Names\r\n"
			+ "Aditi\r\n"
			+ "Ananya\r\n"
			+ "Bhavya\r\n"
			+ "Chhavi\r\n"
			+ "Deepika\r\n"
			+ "Divya\r\n"
			+ "Esha\r\n"
			+ "Hina\r\n"
			+ "Ishita\r\n"
			+ "Jyoti\r\n"
			+ "Kavya\r\n"
			+ "Meera\r\n"
			+ "Nandini\r\n"
			+ "Pallavi\r\n"
			+ "Pooja\r\n"
			+ "Priya\r\n"
			+ "Radhika\r\n"
			+ "Riya\r\n"
			+ "Sakshi\r\n"
			+ "Sanjana\r\n"
			+ "Shreya\r\n"
			+ "Sneha\r\n"
			+ "Swati\r\n"
			+ "Tanya\r\n"
			+ "Vaishnavi\r\n"
			+ "";
}
}
